/**
 * @file taskStore.ts
 * @description Pinia store for task management with tenant-isolated Firestore operations.
 * @author Vasile Chifeac
 * @created 2026-07-16
 * @modified 2026-07-16
 *
 * @notes
 * - Implements Config-Fenced pattern via useFirestore composable (masterChecklist §2.2)
 * - State acts as local cache for offline resilience (§5)
 * - All CRUD ops validated by Firestore Security Rules tenant isolation
 *
 * @dependencies
 * - pinia
 * - src/composables/useFirestore.ts
 * - src/types/models.ts
 *
 * @performance
 * - Firestore reads: 1 read per fetchTasks()
 * - Cache persistence in Pinia state (survives auth refresh)
 */

// ── Vue & Framework ──────────────────────────────────────────────────────────
import { defineStore, acceptHMRUpdate } from "pinia";

// ── Firebase ─────────────────────────────────────────────────────────────────
import { getFunctions, httpsCallable } from "firebase/functions";
import { app } from "@/boot/firebase";

// ── Types ────────────────────────────────────────────────────────────────────
import type {
  Task,
  TaskAIMetadata,
  TaskStatus,
  Workspace,
  WorkspaceAttitude,
  CreateTaskPayload,
  CreateWorkspacePayload,
  RefinedTaskDraft,
} from "@/types/models";

// ── Composables ──────────────────────────────────────────────────────────────
import { useFirestore } from "@/composables/useFirestore";

// ── Utils ────────────────────────────────────────────────────────────────────
// (none)

// ── Stores ───────────────────────────────────────────────────────────────────
// (none)

/**
 * Task store internal state interface.
 */
interface TaskState {
  tasks: Task[];
  workspaces: Workspace[];
  activeWorkspaceId: string | null;
  isLoading: boolean;
  isGeneratingAttitude: boolean;
  /** True while the refineTaskDraft Cloud Function call is in-flight (Step 17). */
  isRefiningTaskDraft: boolean;
  error: string | null;
} /*end TaskState*/

/**
 * Default AI metadata for new tasks.
 * Applied when creating a task without aiMetadata.
 */
const DEFAULT_AI_METADATA: TaskAIMetadata = {
  complexityScore: 5,
  suggestedCategory: "general",
  confidence: 0.5,
  modelVersion: "manual",
  lastAnalyzed: null,
}; /*end DEFAULT_AI_METADATA*/

/**
 * Build complete AI metadata from partial input.
 * Preserves subtasks and qualityAudit generated by AgentePlanner / AI Task Architect.
 */
function buildAIMetadata(metadata?: Partial<TaskAIMetadata>): TaskAIMetadata {
  return metadata
    ? {
        complexityScore: metadata.complexityScore ?? 5,
        suggestedCategory: metadata.suggestedCategory ?? "general",
        confidence: metadata.confidence ?? 0.5,
        modelVersion: metadata.modelVersion ?? "manual",
        lastAnalyzed: metadata.lastAnalyzed ?? null,
        ...(metadata.subtasks ? { subtasks: metadata.subtasks } : {}),
        ...(metadata.qualityAudit ? { qualityAudit: metadata.qualityAudit } : {}),
      }
    : DEFAULT_AI_METADATA;
} /*end buildAIMetadata*/

const WORKSPACES_CACHE_KEY = "opsflow_workspaces_cache";

/**
 * Hydrate/migrate legacy workspace linkedResources to WorkspaceAttitude (Step 10 Fase 1.7).
 */
function hydrateWorkspaceAttitude(ws: Workspace): Workspace {
  if (!ws.attitude && ws.linkedResources) {
    const lr = ws.linkedResources;
    if (lr.doList || lr.dontList || lr.toneOfVoice) {
      ws.attitude = {
        industryScope: ws.category || "Generale",
        tone: lr.toneOfVoice || "operational",
        skills: lr.assignedAgents || [],
        rules: {
          doList: lr.doList || [],
          dontList: lr.dontList || [],
          outputFormat: "markdown",
        },
      };
    }
  }
  return ws;
} /*end hydrateWorkspaceAttitude*/

function loadCachedWorkspaces(): Workspace[] {
  try {
    const raw = localStorage.getItem(WORKSPACES_CACHE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as Workspace[];
    return Array.isArray(parsed) ? parsed.map(hydrateWorkspaceAttitude) : [];
  } catch {
    return [];
  }
} /*end loadCachedWorkspaces*/

function saveCachedWorkspaces(workspaces: Workspace[]): void {
  try {
    localStorage.setItem(WORKSPACES_CACHE_KEY, JSON.stringify(workspaces));
  } catch {
    // Ignore quota error
  }
} /*end saveCachedWorkspaces*/

export const useTaskStore = defineStore("tasks", {
  state: (): TaskState => ({
    tasks: [],
    workspaces: loadCachedWorkspaces(),
    activeWorkspaceId: null,
    isLoading: false,
    isGeneratingAttitude: false,
    isRefiningTaskDraft: false,
    error: null,
  }),

  getters: {
    /**
     * Active workspace object resolved reactively from activeWorkspaceId.
     * Returns null when on the Home Dashboard (no active workspace selected).
     */
    activeWorkspace: (state): Workspace | null => {
      if (!state.activeWorkspaceId || state.workspaces.length === 0) return null;
      return state.workspaces.find((w) => w.id === state.activeWorkspaceId) || null;
    },

    /**
     * Active workspace DBS attitude constitution (Step 10).
     */
    activeWorkspaceAttitude: (state): WorkspaceAttitude | null => {
      if (!state.activeWorkspaceId || state.workspaces.length === 0) return null;
      const active = state.workspaces.find((w) => w.id === state.activeWorkspaceId);
      return active?.attitude || null;
    },

    /**
     * Tasks not yet completed (pending + in-progress).
     * Used for task list view filtering.
     */
    pendingTasks: (state): Task[] => {
      return state.tasks.filter(
        (task) => task.status === "pending" || task.status === "in-progress",
      );
    },

    /**
     * Tasks marked as completed.
     * Used for completion history view.
     */
    completedTasks: (state): Task[] => {
      return state.tasks.filter((task) => task.status === "completed");
    },

    /**
     * Tasks assigned to a specific user.
     * Usage: const myTasks = storeToRefs(useTaskStore()).assignedTasks(taskId)
     */
    assignedTasks: (state) => {
      return (assigneeId: string): Task[] => {
        return state.tasks.filter((task) => task.assignedTo === assigneeId);
      };
    },
  },

  actions: {
    /**
     * Set active workspace by ID or Workspace object and fetch its tasks.
     */
    async setActiveWorkspace(target: Workspace | string | null): Promise<void> {
      if (!target) {
        this.activeWorkspaceId = null;
        return;
      }
      const wsId = typeof target === "string" ? target : target.id;
      this.activeWorkspaceId = wsId;
      await this.fetchWorkspaceTasks(wsId);
    } /*end setActiveWorkspace*/,

    /**
     * Fetch all workspaces for the current tenant.
     */
    async fetchWorkspaces(): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const docs = await firestore.getTenantDocs<Workspace>(firestore.COLLECTIONS.WORKSPACES);
        this.workspaces = docs;
        saveCachedWorkspaces(docs);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to fetch workspaces";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end fetchWorkspaces*/,

    /**
     * Fetch tasks for a specific workspace from nested collection tenants/{tenantId}/workspaces/{workspaceId}/tasks.
     * Also checks flat tasks collection for backwards compatibility.
     */
    async fetchWorkspaceTasks(workspaceId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const nestedTasks = await firestore.getWorkspaceTaskDocs<Task>(workspaceId);
        let legacyTasks: Task[] = [];
        try {
          legacyTasks = await firestore.getTenantDocs<Task>(firestore.COLLECTIONS.TASKS);
        } catch {
          // Legacy tasks collection may be empty or unmigrated
        }
        const filteredLegacy = legacyTasks.filter((t) => t.workspaceId === workspaceId);

        // Merge without duplicates
        const existingIds = new Set(nestedTasks.map((t) => t.id));
        const allTasks = [...nestedTasks];
        for (const lt of filteredLegacy) {
          if (!existingIds.has(lt.id)) {
            allTasks.push(lt);
          }
        }

        // Update local state for this workspace
        this.tasks = this.tasks.filter((t) => t.workspaceId !== workspaceId).concat(allTasks);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to fetch workspace tasks";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end fetchWorkspaceTasks*/,

    /**
     * Fetch all tasks across workspaces.
     */
    async fetchTasks(): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        if (this.workspaces.length === 0) {
          await this.fetchWorkspaces();
        }

        const taskPromises = this.workspaces.map((ws) =>
          firestore.getWorkspaceTaskDocs<Task>(ws.id),
        );
        const nestedResults = await Promise.all(taskPromises);
        let legacyTasks: Task[] = [];
        try {
          legacyTasks = await firestore.getTenantDocs<Task>(firestore.COLLECTIONS.TASKS);
        } catch {
          // Legacy tasks collection may be empty or unmigrated
        }

        const allTasks: Task[] = [];
        const seenIds = new Set<string>();

        for (const list of nestedResults) {
          for (const t of list) {
            allTasks.push(t);
            seenIds.add(t.id);
          }
        }

        for (const lt of legacyTasks) {
          if (!seenIds.has(lt.id)) {
            allTasks.push(lt);
          }
        }

        this.tasks = allTasks;
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to fetch tasks";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end fetchTasks*/,

    /**
     * Create a new task inside a workspace nested collection.
     */
    async createTask(draft: CreateTaskPayload & { workspaceId: string }): Promise<string> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const aiMetadata = buildAIMetadata(draft.aiMetadata);
        const status = draft.status ?? "pending";
        const assignedTo = draft.assignedTo ?? null;

        const taskId = await firestore.addWorkspaceTaskDoc<
          Omit<Task, "id" | "createdAt" | "updatedAt">
        >(draft.workspaceId, {
          title: draft.title,
          description: draft.description,
          workspaceId: draft.workspaceId,
          status,
          assignedTo,
          aiMetadata,
        });

        const newTask: Task = {
          title: draft.title,
          description: draft.description,
          workspaceId: draft.workspaceId,
          status,
          assignedTo,
          aiMetadata,
          id: taskId,
          tenantId: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        } as Task;

        this.tasks.push(newTask);
        return taskId;
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to create task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end createTask*/,

    /**
     * Update task status in Firestore workspace collection.
     */
    async updateTaskStatus(workspaceId: string, taskId: string, status: TaskStatus): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, { status });

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          task.status = status;
          task.updatedAt = new Date();
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update task status";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateTaskStatus*/,

    /**
     * Move a task from source workspace to target workspace.
     */
    async moveTask(
      taskId: string,
      sourceWorkspaceId: string,
      targetWorkspaceId: string,
    ): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.moveWorkspaceTaskDoc(sourceWorkspaceId, targetWorkspaceId, taskId);

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          task.workspaceId = targetWorkspaceId;
          task.updatedAt = new Date();
        }

        // Remove from local tasks list if currently viewing source workspace
        this.tasks = this.tasks.filter(
          (t) => t.workspaceId !== sourceWorkspaceId || t.id !== taskId,
        );
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to move task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end moveTask*/,

    /**
     * Set attitude in-memory for a workspace and persist to localStorage cache (Step 10 Fase 1.7).
     */
    setAttitude(workspaceId: string, attitude: WorkspaceAttitude): void {
      const wsIdx = this.workspaces.findIndex((w) => w.id === workspaceId);
      if (wsIdx !== -1 && this.workspaces[wsIdx]) {
        this.workspaces[wsIdx] = {
          ...this.workspaces[wsIdx],
          attitude,
          updatedAt: new Date(),
        } as Workspace;
      }
      saveCachedWorkspaces(this.workspaces);
    } /*end setAttitude*/,

    /**
     * Update Workspace Attitude in Firestore and local state/cache (Step 10 Fase 1.7).
     */
    async updateWorkspaceAttitude(workspaceId: string, attitude: WorkspaceAttitude): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, {
          attitude,
        });
        this.setAttitude(workspaceId, attitude);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update workspace attitude";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspaceAttitude*/,

    /**
     * Call generateDbsAttitude Cloud Function via Firebase SDK (Vertical Slice Step A - Step 10 Fase 2.5).
     */
    async generateDbsAttitude(workspaceId: string, userPrompt: string): Promise<WorkspaceAttitude> {
      this.isGeneratingAttitude = true;
      this.error = null;

      try {
        const functions = getFunctions(app, "europe-west1");
        const callable = httpsCallable<
          { workspaceId: string; userPrompt: string },
          { success: boolean; attitude: WorkspaceAttitude }
        >(functions, "generateDbsAttitude");

        const res = await callable({ workspaceId, userPrompt });
        if (res.data && res.data.attitude) {
          this.setAttitude(workspaceId, res.data.attitude);
          return res.data.attitude;
        }
        throw new Error("Invalid response from generateDbsAttitude");
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to generate DBS attitude";
        throw err;
      } finally {
        this.isGeneratingAttitude = false;
      }
    } /*end generateDbsAttitude*/,

    /**
     * Call refineTaskDraft Cloud Function via Firebase SDK (AI Task Architect — Step 17).
     *
     * Passes the Workspace DBS Attitude as context for the 3-level stacked prompt.
     * On network failure the raw draft text is NOT reset (fail-safe per piano Step 17 §3.2).
     *
     * @param workspaceId - Target workspace ID.
     * @param rawDraft - Raw informal text note from the user.
     * @returns Structured RefinedTaskDraft for human review in AITaskArchitectModal.
     */
    async refineTaskDraft(workspaceId: string, rawDraft: string): Promise<RefinedTaskDraft> {
      this.isRefiningTaskDraft = true;
      this.error = null;

      try {
        const functions = getFunctions(app, "europe-west1");
        const callable = httpsCallable<
          { workspaceId: string; rawDraft: string; workspaceAttitude?: WorkspaceAttitude },
          { success: boolean; refined: RefinedTaskDraft }
        >(functions, "refineTaskDraft");

        // Inject workspace DBS constitution as context (3-level stacked prompt)
        const workspaceAttitude = this.activeWorkspaceAttitude;

        const payload: {
          workspaceId: string;
          rawDraft: string;
          workspaceAttitude?: WorkspaceAttitude;
        } = {
          workspaceId,
          rawDraft,
          ...(workspaceAttitude ? { workspaceAttitude } : {}),
        };

        const res = await callable(payload);
        if (res.data && res.data.refined) {
          return res.data.refined;
        }
        throw new Error("Risposta non valida da refineTaskDraft");
      } catch (err) {
        // Fail-safe: set error but do NOT reset rawDraft (handled in component)
        this.error = err instanceof Error ? err.message : "Errore raffinamento task IA";
        throw err;
      } finally {
        this.isRefiningTaskDraft = false;
      }
    } /*end refineTaskDraft*/,

    /**
     * @deprecated Use updateWorkspaceAttitude instead (Step 10 Fase 1.7).
     * Update the dynamic system prompt (AI attitude) of a Workspace.
     */
    async updateWorkspacePrompt(workspaceId: string, systemPrompt: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, {
          systemPrompt,
        });

        const ws = this.workspaces.find((w) => w.id === workspaceId);
        if (ws) {
          ws.systemPrompt = systemPrompt;
          ws.updatedAt = new Date();
        }
        saveCachedWorkspaces(this.workspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update workspace prompt";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspacePrompt*/,

    /**
     * Update Workspace Linked Google Resources and Attitude Configuration.
     */
    async updateWorkspaceLinkedResources(
      workspaceId: string,
      linkedResources: Partial<Workspace["linkedResources"]>,
      systemPrompt?: string,
    ): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const ws = this.workspaces.find((w) => w.id === workspaceId);
        const mergedResources = {
          ...ws?.linkedResources,
          ...linkedResources,
        };

        const updatePayload: Partial<Workspace> = {
          linkedResources: mergedResources,
        };
        if (systemPrompt !== undefined) {
          updatePayload.systemPrompt = systemPrompt;
        }

        await firestore.updateTenantDoc(
          firestore.COLLECTIONS.WORKSPACES,
          workspaceId,
          updatePayload,
        );

        if (ws) {
          ws.linkedResources = mergedResources;
          if (systemPrompt !== undefined) {
            ws.systemPrompt = systemPrompt;
          }
          ws.updatedAt = new Date();
        }
        saveCachedWorkspaces(this.workspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update linked resources";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspaceLinkedResources*/,

    /**
     * Update task details (title, description) in Firestore workspace collection.
     */
    async updateTask(workspaceId: string, taskId: string, updates: Partial<Task>): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, updates);

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          Object.assign(task, updates);
          task.updatedAt = new Date();
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateTask*/,

    /**
     * Delete a task from Firestore workspace collection.
     */
    async deleteTask(workspaceId: string, taskId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.deleteWorkspaceTaskDoc(workspaceId, taskId);
        this.tasks = this.tasks.filter((t) => t.id !== taskId);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to delete task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end deleteTask*/,

    /**
     * Create a new workspace.
     * Auto-injects tenantId via addTenantDoc.
     */
    async createWorkspace(draft: CreateWorkspacePayload): Promise<string> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const workspaceData: Omit<Workspace, "id" | "createdAt" | "updatedAt"> = {
          name: draft.name,
          description: draft.description ?? "",
          tenantId: "",
        };
        if (draft.icon !== undefined) {
          workspaceData.icon = draft.icon;
        }

        const workspaceId = await firestore.addTenantDoc<
          Omit<Workspace, "id" | "createdAt" | "updatedAt">
        >(firestore.COLLECTIONS.WORKSPACES, workspaceData);

        const newWorkspace: Workspace = {
          id: workspaceId,
          name: draft.name,
          description: draft.description ?? "",
          tenantId: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        };
        if (draft.icon !== undefined) {
          newWorkspace.icon = draft.icon;
        }

        this.workspaces.push(newWorkspace);
        saveCachedWorkspaces(this.workspaces);
        return workspaceId;
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to create workspace";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end createWorkspace*/,
    /**
     * Update workspace in Firestore and optimistic local cache.
     */
    async updateWorkspace(workspaceId: string, updates: Partial<Workspace>): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, updates);

        const ws = this.workspaces.find((w) => w.id === workspaceId);
        if (ws) {
          Object.assign(ws, updates);
          ws.updatedAt = new Date();
          saveCachedWorkspaces(this.workspaces);
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update workspace";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspace*/,

    /**
     * Delete workspace from Firestore and local cache.
     */
    async deleteWorkspace(workspaceId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.deleteWorkspaceDoc(workspaceId);
        this.workspaces = this.workspaces.filter((w) => w.id !== workspaceId);
        this.tasks = this.tasks.filter((t) => t.workspaceId !== workspaceId);
        saveCachedWorkspaces(this.workspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to delete workspace";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end deleteWorkspace*/,

    /**
     * Clear error state.
     * Call from component when snackbar is dismissed.
     */
    clearError(): void {
      this.error = null;
    } /*end clearError*/,
  },
});

// HMR support for development
if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useTaskStore, import.meta.hot));
}
