/**
 * @file taskStore.ts
 * @description Pinia store for task management with tenant-isolated Firestore operations.
 * @author Vasile Chifeac
 * @created 2026-07-16
 * @modified 2026-07-16
 *
 * @notes
 * - Implements Config-Fenced pattern via useFirestore composable (masterChecklist §2.2)
 * - State acts as local cache for offline resilience (§5)
 * - All CRUD ops validated by Firestore Security Rules tenant isolation
 *
 * @dependencies
 * - pinia
 * - src/composables/useFirestore.ts
 * - src/types/models.ts
 *
 * @performance
 * - Firestore reads: 1 read per fetchTasks()
 * - Cache persistence in Pinia state (survives auth refresh)
 */

// ── Vue & Framework ──────────────────────────────────────────────────────────
import { defineStore, acceptHMRUpdate } from "pinia";

// ── Firebase ─────────────────────────────────────────────────────────────────
import { getFunctions, httpsCallable } from "firebase/functions";
import { app } from "@/boot/firebase";

// ── Types ────────────────────────────────────────────────────────────────────
import type {
  Task,
  TaskAIMetadata,
  TaskStatus,
  Workspace,
  WorkspaceAttitude,
  CreateTaskPayload,
  CreateWorkspacePayload,
  RefinedTaskDraft,
  UserUsageQuota,
} from "@/types/models";

// ── Stores ───────────────────────────────────────────────────────────────────
import { useAuthStore } from "@/stores/authStore";

// ── Composables ──────────────────────────────────────────────────────────────
import { useFirestore } from "@/composables/useFirestore";

// ── Utils ────────────────────────────────────────────────────────────────────
// (none)

// ── Components ───────────────────────────────────────────────────────────────
// (none)

/**
 * Task store internal state interface.
 */
interface TaskState {
  tasks: Task[];
  workspaces: Workspace[];
  activeWorkspaceId: string | null;
  isLoading: boolean;
  isGeneratingAttitude: boolean;
  /** True while the refineTaskDraft Cloud Function call is in-flight (Step 17). */
  isRefiningTaskDraft: boolean;
  error: string | null;
} /*end TaskState*/

const USER_QUOTA_PREFIX = "opsflow_user_quota_";

function loadCachedUserQuota(uid?: string): UserUsageQuota {
  if (!uid) return { createdTasksTotal: 0, deletedTasksCount: 0 };
  try {
    const raw = localStorage.getItem(`${USER_QUOTA_PREFIX}${uid}`);
    if (!raw) return { createdTasksTotal: 0, deletedTasksCount: 0 };
    const parsed = JSON.parse(raw) as UserUsageQuota;
    return {
      createdTasksTotal:
        typeof parsed.createdTasksTotal === "number" ? parsed.createdTasksTotal : 0,
      deletedTasksCount:
        typeof parsed.deletedTasksCount === "number" ? parsed.deletedTasksCount : 0,
    };
  } catch {
    return { createdTasksTotal: 0, deletedTasksCount: 0 };
  }
} /*end loadCachedUserQuota*/

function saveCachedUserQuota(uid: string, quota: UserUsageQuota): void {
  try {
    localStorage.setItem(`${USER_QUOTA_PREFIX}${uid}`, JSON.stringify(quota));
  } catch {
    // Ignore storage quota errors
  }
} /*end saveCachedUserQuota*/

/**
 * Default AI metadata for new tasks.
 * Applied when creating a task without aiMetadata.
 */
const DEFAULT_AI_METADATA: TaskAIMetadata = {
  complexityScore: 5,
  suggestedCategory: "general",
  confidence: 0.5,
  modelVersion: "manual",
  lastAnalyzed: null,
}; /*end DEFAULT_AI_METADATA*/

/**
 * Build complete AI metadata from partial input.
 * Preserves subtasks and qualityAudit generated by AgentePlanner / AI Task Architect.
 */
function buildAIMetadata(metadata?: Partial<TaskAIMetadata>): TaskAIMetadata {
  return metadata
    ? {
        complexityScore: metadata.complexityScore ?? 5,
        suggestedCategory: metadata.suggestedCategory ?? "general",
        confidence: metadata.confidence ?? 0.5,
        modelVersion: metadata.modelVersion ?? "manual",
        lastAnalyzed: metadata.lastAnalyzed ?? null,
        ...(metadata.subtasks ? { subtasks: metadata.subtasks } : {}),
        ...(metadata.qualityAudit ? { qualityAudit: metadata.qualityAudit } : {}),
      }
    : DEFAULT_AI_METADATA;
} /*end buildAIMetadata*/

function getCurrentCachedUserId(): string | null {
  try {
    const raw = localStorage.getItem("opsflow_user_session");
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { uid?: string };
    return parsed?.uid ?? null;
  } catch {
    return null;
  }
} /*end getCurrentCachedUserId*/

function getWorkspacesCacheKey(): string {
  const uid = getCurrentCachedUserId();
  return uid ? `opsflow_user_${uid}_workspaces` : "opsflow_workspaces_cache";
} /*end getWorkspacesCacheKey*/

function getActiveWorkspaceCacheKey(): string {
  const uid = getCurrentCachedUserId();
  return uid ? `opsflow_user_${uid}_active_workspace_id` : "opsflow_active_workspace_id";
} /*end getActiveWorkspaceCacheKey*/

/**
 * Hydrate/migrate legacy workspace linkedResources to WorkspaceAttitude (Step 10 Fase 1.7).
 */
function hydrateWorkspaceAttitude(ws: Workspace): Workspace {
  if (!ws.attitude && ws.linkedResources) {
    const lr = ws.linkedResources;
    if (lr.doList || lr.dontList || lr.toneOfVoice) {
      ws.attitude = {
        industryScope: ws.category || "Generale",
        tone: lr.toneOfVoice || "operational",
        skills: lr.assignedAgents || [],
        rules: {
          doList: lr.doList || [],
          dontList: lr.dontList || [],
          outputFormat: "markdown",
        },
      };
    }
  }
  return ws;
} /*end hydrateWorkspaceAttitude*/

function loadCachedWorkspaces(): Workspace[] {
  try {
    const raw = localStorage.getItem(getWorkspacesCacheKey());
    if (!raw) return [];
    const parsed = JSON.parse(raw) as Workspace[];
    return Array.isArray(parsed) ? parsed.map(hydrateWorkspaceAttitude) : [];
  } catch {
    return [];
  }
} /*end loadCachedWorkspaces*/

function loadCachedActiveWorkspaceId(): string | null {
  try {
    return localStorage.getItem(getActiveWorkspaceCacheKey()) || null;
  } catch {
    return null;
  }
} /*end loadCachedActiveWorkspaceId*/

function saveCachedActiveWorkspaceId(id: string | null): void {
  try {
    const key = getActiveWorkspaceCacheKey();
    if (id) {
      localStorage.setItem(key, id);
    } else {
      localStorage.removeItem(key);
    }
  } catch {
    // Ignore quota error
  }
} /*end saveCachedActiveWorkspaceId*/

function saveCachedWorkspaces(workspaces: Workspace[]): void {
  try {
    localStorage.setItem(getWorkspacesCacheKey(), JSON.stringify(workspaces));
  } catch {
    // Ignore quota error
  }
} /*end saveCachedWorkspaces*/

export const useTaskStore = defineStore("tasks", {
  state: (): TaskState => ({
    tasks: [],
    workspaces: loadCachedWorkspaces(),
    activeWorkspaceId: loadCachedActiveWorkspaceId(),
    isLoading: false,
    isGeneratingAttitude: false,
    isRefiningTaskDraft: false,
    error: null,
  }),

  getters: {
    /**
     * Active workspace object resolved reactively from activeWorkspaceId.
     * Returns null when on the Home Dashboard (no active workspace selected).
     */
    activeWorkspace: (state): Workspace | null => {
      if (!state.activeWorkspaceId || state.workspaces.length === 0) return null;
      return state.workspaces.find((w) => w.id === state.activeWorkspaceId) || null;
    },

    /**
     * Active workspace DBS attitude constitution (Step 10).
     */
    activeWorkspaceAttitude: (state): WorkspaceAttitude | null => {
      if (!state.activeWorkspaceId || state.workspaces.length === 0) return null;
      const active = state.workspaces.find((w) => w.id === state.activeWorkspaceId);
      return active?.attitude || null;
    },

    /**
     * Tasks not yet completed (pending + in-progress).
     * Used for task list view filtering.
     */
    pendingTasks: (state): Task[] => {
      return state.tasks.filter(
        (task) => task.status === "pending" || task.status === "in-progress",
      );
    },

    /**
     * Tasks marked as completed.
     * Used for completion history view.
     */
    completedTasks: (state): Task[] => {
      return state.tasks.filter((task) => task.status === "completed");
    },

    /**
     * Tasks assigned to a specific user.
     * Usage: const myTasks = storeToRefs(useTaskStore()).assignedTasks(taskId)
     */
    assignedTasks: (state) => {
      return (assigneeId: string): Task[] => {
        return state.tasks.filter((task) => task.assignedTo === assigneeId);
      };
    },
  },

  actions: {
    /**
     * Set active workspace by ID or Workspace object and fetch its tasks.
     */
    async setActiveWorkspace(target: Workspace | string | null): Promise<void> {
      if (!target) {
        this.activeWorkspaceId = null;
        saveCachedActiveWorkspaceId(null);
        return;
      }
      const wsId = typeof target === "string" ? target : target.id;
      this.activeWorkspaceId = wsId;
      saveCachedActiveWorkspaceId(wsId);
      await this.fetchWorkspaceTasks(wsId);
    } /*end setActiveWorkspace*/,

    /**
     * Fetch all workspaces for the current tenant.
     */
    async fetchWorkspaces(): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const docs = await firestore.getTenantDocs<Workspace>(firestore.COLLECTIONS.WORKSPACES);
        const authStore = useAuthStore();
        let visibleWorkspaces = docs;
        if (authStore.role === "user" && authStore.user) {
          const userEmail = authStore.user.email.toLowerCase();
          const userUid = authStore.user.uid;
          visibleWorkspaces = docs.filter((ws) => {
            // Workspaces without assigned members are strictly private to Owner/Admin (§7.4 .logicFlow)
            if (!ws.assignedMembers || ws.assignedMembers.length === 0) return false;
            return ws.assignedMembers.some((m) => m.toLowerCase() === userEmail || m === userUid);
          });
        }
        this.workspaces = visibleWorkspaces;
        saveCachedWorkspaces(visibleWorkspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to fetch workspaces";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end fetchWorkspaces*/,

    /**
     * Fetch tasks for a specific workspace from nested collection tenants/{tenantId}/workspaces/{workspaceId}/tasks.
     * Also checks flat tasks collection for backwards compatibility.
     */
    async fetchWorkspaceTasks(workspaceId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const nestedTasks = await firestore.getWorkspaceTaskDocs<Task>(workspaceId);
        let legacyTasks: Task[] = [];
        try {
          legacyTasks = await firestore.getTenantDocs<Task>(firestore.COLLECTIONS.TASKS);
        } catch {
          // Legacy tasks collection may be empty or unmigrated
        }
        const filteredLegacy = legacyTasks.filter((t) => t.workspaceId === workspaceId);

        // Merge without duplicates
        const existingIds = new Set(nestedTasks.map((t) => t.id));
        const allTasks = [...nestedTasks];
        for (const lt of filteredLegacy) {
          if (!existingIds.has(lt.id)) {
            allTasks.push(lt);
          }
        }

        // Step 26: Scoped visibility for 'user' role (Workspace vs Single Task access)
        const authStore = useAuthStore();
        let visibleTasks = allTasks;
        if (authStore.role === "user" && authStore.user) {
          const userEmail = authStore.user.email.toLowerCase();
          const userUid = authStore.user.uid;
          const currentWs = this.workspaces.find((w) => w.id === workspaceId);
          const isWorkspaceMember = Boolean(
            currentWs?.assignedMembers &&
            currentWs.assignedMembers.some((m) => m.toLowerCase() === userEmail || m === userUid),
          );

          if (!isWorkspaceMember) {
            // Task-scoped collaborator: user only sees tasks where they are explicitly assigned
            visibleTasks = allTasks.filter(
              (t) =>
                t.assignedTo === userUid ||
                (t.assignedMembers &&
                  t.assignedMembers.some((m) => m.toLowerCase() === userEmail || m === userUid)),
            );
          }
        }

        // Update local state for this workspace
        this.tasks = this.tasks.filter((t) => t.workspaceId !== workspaceId).concat(visibleTasks);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to fetch workspace tasks";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end fetchWorkspaceTasks*/,

    /**
     * Fetch all tasks across workspaces.
     */
    async fetchTasks(): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        if (this.workspaces.length === 0) {
          await this.fetchWorkspaces();
        }

        const taskPromises = this.workspaces.map((ws) =>
          firestore.getWorkspaceTaskDocs<Task>(ws.id),
        );
        const nestedResults = await Promise.all(taskPromises);
        let legacyTasks: Task[] = [];
        try {
          legacyTasks = await firestore.getTenantDocs<Task>(firestore.COLLECTIONS.TASKS);
        } catch {
          // Legacy tasks collection may be empty or unmigrated
        }

        const allTasks: Task[] = [];
        const seenIds = new Set<string>();

        for (const list of nestedResults) {
          for (const t of list) {
            allTasks.push(t);
            seenIds.add(t.id);
          }
        }

        for (const lt of legacyTasks) {
          if (!seenIds.has(lt.id)) {
            allTasks.push(lt);
          }
        }

        this.tasks = allTasks;
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to fetch tasks";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end fetchTasks*/,

    /**
     * Create a new task inside a workspace nested collection.
     */
    async createTask(draft: CreateTaskPayload & { workspaceId: string }): Promise<string> {
      const firestore = useFirestore();
      const authStore = useAuthStore();

      // Step 26: Freemium Quota Check
      const quotaCheck = this.canCreateTask(authStore.role, authStore.user?.uid);
      if (!quotaCheck.allowed) {
        throw new Error(quotaCheck.reason || "Quota limite per i task raggiunta.");
      }

      this.isLoading = true;
      this.error = null;

      try {
        const aiMetadata = buildAIMetadata(draft.aiMetadata);
        const status = draft.status ?? "pending";
        const assignedTo = draft.assignedTo ?? null;

        const taskId = await firestore.addWorkspaceTaskDoc<
          Omit<Task, "id" | "createdAt" | "updatedAt">
        >(draft.workspaceId, {
          title: draft.title,
          description: draft.description,
          workspaceId: draft.workspaceId,
          status,
          assignedTo,
          aiMetadata,
          assignedMembers: draft.assignedMembers ?? [],
        });

        const newTask: Task = {
          title: draft.title,
          description: draft.description,
          workspaceId: draft.workspaceId,
          status,
          assignedTo,
          assignedMembers: draft.assignedMembers ?? [],
          aiMetadata,
          id: taskId,
          tenantId: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        } as Task;

        this.tasks.push(newTask);
        if (authStore.user?.uid) {
          this.incrementCreatedTasks(authStore.user.uid);
        }
        return taskId;
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to create task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end createTask*/,

    /**
     * Update task status in Firestore workspace collection.
     */
    async updateTaskStatus(workspaceId: string, taskId: string, status: TaskStatus): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, { status });

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          task.status = status;
          task.updatedAt = new Date();
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update task status";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateTaskStatus*/,

    /**
     * Move a task from source workspace to target workspace.
     */
    async moveTask(
      taskId: string,
      sourceWorkspaceId: string,
      targetWorkspaceId: string,
    ): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.moveWorkspaceTaskDoc(sourceWorkspaceId, targetWorkspaceId, taskId);

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          task.workspaceId = targetWorkspaceId;
          task.updatedAt = new Date();
        }

        // Remove from local tasks list if currently viewing source workspace
        this.tasks = this.tasks.filter(
          (t) => t.workspaceId !== sourceWorkspaceId || t.id !== taskId,
        );
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to move task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end moveTask*/,

    /**
     * Set attitude in-memory for a workspace and persist to localStorage cache (Step 10 Fase 1.7).
     */
    setAttitude(workspaceId: string, attitude: WorkspaceAttitude): void {
      const wsIdx = this.workspaces.findIndex((w) => w.id === workspaceId);
      if (wsIdx !== -1 && this.workspaces[wsIdx]) {
        this.workspaces[wsIdx] = {
          ...this.workspaces[wsIdx],
          attitude,
          updatedAt: new Date(),
        } as Workspace;
      }
      saveCachedWorkspaces(this.workspaces);
    } /*end setAttitude*/,

    /**
     * Update Workspace Attitude in Firestore and local state/cache (Step 10 Fase 1.7).
     */
    async updateWorkspaceAttitude(workspaceId: string, attitude: WorkspaceAttitude): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, {
          attitude,
        });
        this.setAttitude(workspaceId, attitude);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update workspace attitude";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspaceAttitude*/,

    /**
     * Call generateDbsAttitude Cloud Function via Firebase SDK (Vertical Slice Step A - Step 10 Fase 2.5).
     */
    async generateDbsAttitude(workspaceId: string, userPrompt: string): Promise<WorkspaceAttitude> {
      this.isGeneratingAttitude = true;
      this.error = null;

      try {
        const functions = getFunctions(app, "europe-west1");
        const callable = httpsCallable<
          { workspaceId: string; userPrompt: string },
          { success: boolean; attitude: WorkspaceAttitude }
        >(functions, "generateDbsAttitude");

        const res = await callable({ workspaceId, userPrompt });
        if (res.data && res.data.attitude) {
          this.setAttitude(workspaceId, res.data.attitude);
          return res.data.attitude;
        }
        throw new Error("Invalid response from generateDbsAttitude");
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to generate DBS attitude";
        throw err;
      } finally {
        this.isGeneratingAttitude = false;
      }
    } /*end generateDbsAttitude*/,

    /**
     * Call refineTaskDraft Cloud Function via Firebase SDK (AI Task Architect — Step 17).
     *
     * Passes the Workspace DBS Attitude as context for the 3-level stacked prompt.
     * On network failure the raw draft text is NOT reset (fail-safe per piano Step 17 §3.2).
     *
     * @param workspaceId - Target workspace ID.
     * @param rawDraft - Raw informal text note from the user.
     * @returns Structured RefinedTaskDraft for human review in AITaskArchitectModal.
     */
    async refineTaskDraft(workspaceId: string, rawDraft: string): Promise<RefinedTaskDraft> {
      this.isRefiningTaskDraft = true;
      this.error = null;

      try {
        const functions = getFunctions(app, "europe-west1");
        const callable = httpsCallable<
          { workspaceId: string; rawDraft: string; workspaceAttitude?: WorkspaceAttitude },
          { success: boolean; refined: RefinedTaskDraft }
        >(functions, "refineTaskDraft");

        // Inject workspace DBS constitution as context (3-level stacked prompt)
        const workspaceAttitude = this.activeWorkspaceAttitude;

        const payload: {
          workspaceId: string;
          rawDraft: string;
          workspaceAttitude?: WorkspaceAttitude;
        } = {
          workspaceId,
          rawDraft,
          ...(workspaceAttitude ? { workspaceAttitude } : {}),
        };

        const res = await callable(payload);
        if (res.data && res.data.refined) {
          return res.data.refined;
        }
        throw new Error("Risposta non valida da refineTaskDraft");
      } catch (err) {
        // Fail-safe: set error but do NOT reset rawDraft (handled in component)
        this.error = err instanceof Error ? err.message : "Errore raffinamento task IA";
        throw err;
      } finally {
        this.isRefiningTaskDraft = false;
      }
    } /*end refineTaskDraft*/,

    /**
     * @deprecated Use updateWorkspaceAttitude instead (Step 10 Fase 1.7).
     * Update the dynamic system prompt (AI attitude) of a Workspace.
     */
    async updateWorkspacePrompt(workspaceId: string, systemPrompt: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, {
          systemPrompt,
        });

        const ws = this.workspaces.find((w) => w.id === workspaceId);
        if (ws) {
          ws.systemPrompt = systemPrompt;
          ws.updatedAt = new Date();
        }
        saveCachedWorkspaces(this.workspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update workspace prompt";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspacePrompt*/,

    /**
     * Update Workspace Linked Google Resources and Attitude Configuration.
     */
    async updateWorkspaceLinkedResources(
      workspaceId: string,
      linkedResources: Partial<Workspace["linkedResources"]>,
      systemPrompt?: string,
    ): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const ws = this.workspaces.find((w) => w.id === workspaceId);
        const mergedResources = {
          ...ws?.linkedResources,
          ...linkedResources,
        };

        const updatePayload: Partial<Workspace> = {
          linkedResources: mergedResources,
        };
        if (systemPrompt !== undefined) {
          updatePayload.systemPrompt = systemPrompt;
        }

        if (mergedResources.isOAuthConnected) {
          const connectedEmail = (
            mergedResources.googleEmail ||
            ws?.googleIntegration?.connectedEmail ||
            ""
          ).trim();
          updatePayload.googleIntegration = {
            connected: true,
            connectedEmail,
            connectedAt: ws?.googleIntegration?.connectedAt || new Date().toISOString(),
          };
        }

        await firestore.updateTenantDoc(
          firestore.COLLECTIONS.WORKSPACES,
          workspaceId,
          updatePayload,
        );

        if (ws) {
          ws.linkedResources = mergedResources;
          if (systemPrompt !== undefined) {
            ws.systemPrompt = systemPrompt;
          }
          if (updatePayload.googleIntegration) {
            ws.googleIntegration = updatePayload.googleIntegration;
          }
          ws.updatedAt = new Date();
        }
        saveCachedWorkspaces(this.workspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update linked resources";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspaceLinkedResources*/,

    /**
     * Update task details (title, description) in Firestore workspace collection.
     */
    async updateTask(workspaceId: string, taskId: string, updates: Partial<Task>): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, updates);

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          Object.assign(task, updates);
          task.updatedAt = new Date();
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateTask*/,

    /**
     * Delete a task from Firestore workspace collection.
     */
    async deleteTask(workspaceId: string, taskId: string): Promise<void> {
      const firestore = useFirestore();
      const authStore = useAuthStore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.deleteWorkspaceTaskDoc(workspaceId, taskId);
        this.tasks = this.tasks.filter((t) => t.id !== taskId);
        if (authStore.user?.uid) {
          this.incrementDeletedTasks(authStore.user.uid);
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to delete task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end deleteTask*/,

    /**
     * Archive a task in workspace (moves it to the archived section).
     */
    async archiveTask(workspaceId: string, taskId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        const archivedAt = new Date().toISOString();
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, {
          archived: true,
          archivedAt,
        });

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          task.archived = true;
          task.archivedAt = archivedAt;
          task.updatedAt = new Date();
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to archive task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end archiveTask*/,

    /**
     * Restore an archived task back to active workspace tasks.
     */
    async restoreTask(workspaceId: string, taskId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, {
          archived: false,
          archivedAt: null,
        });

        const task = this.tasks.find((t) => t.id === taskId);
        if (task) {
          task.archived = false;
          task.archivedAt = null;
          task.updatedAt = new Date();
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to restore task";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end restoreTask*/,

    /**
     * Toggle the pinned status of a task in the workspace.
     */
    async togglePinTask(workspaceId: string, taskId: string): Promise<void> {
      const firestore = useFirestore();
      const task = this.tasks.find((t) => t.id === taskId);
      if (!task) return;

      const nextPinned = !task.pinned;

      try {
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, {
          pinned: nextPinned,
        });

        task.pinned = nextPinned;
        task.updatedAt = new Date();
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to toggle pin task";
        throw err;
      }
    } /*end togglePinTask*/,

    /**
     * Reorder tasks in the workspace by updating their `order` index.
     */
    async reorderTasks(workspaceId: string, orderedTaskIds: string[]): Promise<void> {
      const firestore = useFirestore();

      // Optimistic update in local Pinia state
      orderedTaskIds.forEach((id, idx) => {
        const t = this.tasks.find((task) => task.id === id);
        if (t) {
          t.order = idx;
        }
      });

      // Persist in background to Firestore
      try {
        const updatePromises = orderedTaskIds.map((id, idx) =>
          firestore.updateWorkspaceTaskDoc(workspaceId, id, { order: idx }).catch(() => {}),
        );
        await Promise.all(updatePromises);
      } catch (err) {
        console.warn("[taskStore:reorderTasks] Error updating task order in Firestore:", err);
      }
    } /*end reorderTasks*/,

    /**
     * Create a new workspace.
     * Auto-injects tenantId via addTenantDoc.
     */
    async createWorkspace(draft: CreateWorkspacePayload): Promise<string> {
      const firestore = useFirestore();
      const authStore = useAuthStore();

      // Step 26: Freemium Quota Check
      const quotaCheck = this.canCreateWorkspace(authStore.role);
      if (!quotaCheck.allowed) {
        throw new Error(quotaCheck.reason || "Quota limite per i workspace raggiunta.");
      }

      this.isLoading = true;
      this.error = null;

      try {
        const membersList = draft.assignedMembers ? [...draft.assignedMembers] : [];
        if (authStore.user?.email && !membersList.includes(authStore.user.email)) {
          membersList.push(authStore.user.email);
        }

        const workspaceData: Omit<Workspace, "id" | "createdAt" | "updatedAt"> = {
          name: draft.name,
          description: draft.description ?? "",
          tenantId: "",
        };
        if (draft.icon !== undefined) {
          workspaceData.icon = draft.icon;
        }
        if (membersList.length > 0) {
          workspaceData.assignedMembers = membersList;
        }

        const workspaceId = await firestore.addTenantDoc<
          Omit<Workspace, "id" | "createdAt" | "updatedAt">
        >(firestore.COLLECTIONS.WORKSPACES, workspaceData);

        const newWorkspace: Workspace = {
          id: workspaceId,
          name: draft.name,
          description: draft.description ?? "",
          tenantId: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        };
        if (draft.icon !== undefined) {
          newWorkspace.icon = draft.icon;
        }
        if (membersList.length > 0) {
          newWorkspace.assignedMembers = membersList;
        }

        this.workspaces.push(newWorkspace);
        saveCachedWorkspaces(this.workspaces);
        return workspaceId;
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to create workspace";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end createWorkspace*/,
    /**
     * Update workspace in Firestore and optimistic local cache.
     */
    async updateWorkspace(workspaceId: string, updates: Partial<Workspace>): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, updates);

        const ws = this.workspaces.find((w) => w.id === workspaceId);
        if (ws) {
          Object.assign(ws, updates);
          ws.updatedAt = new Date();
          saveCachedWorkspaces(this.workspaces);
        }
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to update workspace";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end updateWorkspace*/,

    /**
     * Delete workspace from Firestore and local cache.
     */
    async deleteWorkspace(workspaceId: string): Promise<void> {
      const firestore = useFirestore();

      this.isLoading = true;
      this.error = null;

      try {
        await firestore.deleteWorkspaceDoc(workspaceId);
        this.workspaces = this.workspaces.filter((w) => w.id !== workspaceId);
        this.tasks = this.tasks.filter((t) => t.workspaceId !== workspaceId);
        saveCachedWorkspaces(this.workspaces);
      } catch (err) {
        this.error = err instanceof Error ? err.message : "Failed to delete workspace";
        throw err;
      } finally {
        this.isLoading = false;
      }
    } /*end deleteWorkspace*/,

    // ── Step 26: User Quota & Freemium Governance ─────────────────────────────
    getUserQuota(uid?: string): UserUsageQuota {
      return loadCachedUserQuota(uid);
    } /*end getUserQuota*/,

    incrementCreatedTasks(uid?: string): void {
      if (!uid) return;
      const q = loadCachedUserQuota(uid);
      q.createdTasksTotal += 1;
      saveCachedUserQuota(uid, q);
    } /*end incrementCreatedTasks*/,

    incrementDeletedTasks(uid?: string): void {
      if (!uid) return;
      const q = loadCachedUserQuota(uid);
      q.deletedTasksCount += 1;
      saveCachedUserQuota(uid, q);
    } /*end incrementDeletedTasks*/,

    canCreateWorkspace(role: string): { allowed: boolean; reason?: string } {
      if (role === "owner" || role === "superadmin") {
        return { allowed: true };
      }
      if (role === "admin") {
        return { allowed: true };
      }
      // Role 'user' (Free tier)
      if (this.workspaces.length >= 1) {
        return {
          allowed: false,
          reason:
            "Gli utenti con piano Free possono gestire al massimo 1 Workspace. Per creare più workspace o collaborare senza limiti, effettua l'upgrade a un piano Pro/Business o richiedi l'invito al tuo Admin.",
        };
      }
      return { allowed: true };
    } /*end canCreateWorkspace*/,

    canCreateTask(role: string, uid?: string): { allowed: boolean; reason?: string } {
      if (role === "owner" || role === "superadmin") {
        return { allowed: true };
      }
      if (role === "admin") {
        return { allowed: true };
      }
      // Role 'user' (Free tier)
      const quota = this.getUserQuota(uid);
      const currentTotal = this.tasks.length; // active + archived in current workspace
      if (currentTotal >= 3) {
        return {
          allowed: false,
          reason:
            "Hai raggiunto il limite massimo di 3 Task contemporanei (inclusi archiviati). Per creare un nuovo task, elimina un task esistente (fino a 3 cancellazioni concesse) o passa a un piano Pro.",
        };
      }
      if (quota.createdTasksTotal >= 6) {
        return {
          allowed: false,
          reason:
            "Hai raggiunto il tetto massimo del piano Free di 6 Task totali nel ciclo di vita (3 iniziali + 3 per rimpiazzo cancellazioni). Effettua l'upgrade a Pro per sbloccare task illimitati.",
        };
      }
      if (quota.deletedTasksCount >= 3 && quota.createdTasksTotal >= 3 + quota.deletedTasksCount) {
        return {
          allowed: false,
          reason:
            "Hai già usufruito di tutte le 3 cancellazioni consentite per il piano Free. Effettua l'upgrade a Pro per continuare a creare task.",
        };
      }
      return { allowed: true };
    } /*end canCreateTask*/,

    // ── Step 26: Workspace & Task Member Assignment ───────────────────────────
    async assignMemberToWorkspace(workspaceId: string, emailOrUid: string): Promise<void> {
      const firestore = useFirestore();
      const ws = this.workspaces.find((w) => w.id === workspaceId);
      if (!ws) return;
      const current = ws.assignedMembers ? [...ws.assignedMembers] : [];
      if (!current.includes(emailOrUid)) {
        current.push(emailOrUid);
        await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, {
          assignedMembers: current,
        });
        ws.assignedMembers = current;
        saveCachedWorkspaces(this.workspaces);
      }
    } /*end assignMemberToWorkspace*/,

    async removeMemberFromWorkspace(workspaceId: string, emailOrUid: string): Promise<void> {
      const firestore = useFirestore();
      const ws = this.workspaces.find((w) => w.id === workspaceId);
      if (!ws || !ws.assignedMembers) return;
      const updated = ws.assignedMembers.filter((m) => m !== emailOrUid);
      await firestore.updateTenantDoc(firestore.COLLECTIONS.WORKSPACES, workspaceId, {
        assignedMembers: updated,
      });
      ws.assignedMembers = updated;
      saveCachedWorkspaces(this.workspaces);
    } /*end removeMemberFromWorkspace*/,

    async assignMemberToTask(
      workspaceId: string,
      taskId: string,
      emailOrUid: string,
    ): Promise<void> {
      const firestore = useFirestore();
      const task = this.tasks.find((t) => t.id === taskId);
      if (!task) return;
      const current = task.assignedMembers ? [...task.assignedMembers] : [];
      if (!current.includes(emailOrUid)) {
        current.push(emailOrUid);
        await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, {
          assignedMembers: current,
        });
        task.assignedMembers = current;
      }
    } /*end assignMemberToTask*/,

    async removeMemberFromTask(
      workspaceId: string,
      taskId: string,
      emailOrUid: string,
    ): Promise<void> {
      const firestore = useFirestore();
      const task = this.tasks.find((t) => t.id === taskId);
      if (!task || !task.assignedMembers) return;
      const updated = task.assignedMembers.filter((m) => m !== emailOrUid);
      await firestore.updateWorkspaceTaskDoc(workspaceId, taskId, {
        assignedMembers: updated,
      });
      task.assignedMembers = updated;
    } /*end removeMemberFromTask*/,

    /**
     * Purge in-memory workspace and task state on logout (§5 AGENTS.md, §7.4 .logicFlow).
     */
    resetWorkspaceState(): void {
      this.tasks = [];
      this.workspaces = [];
      this.activeWorkspaceId = null;
      this.error = null;
    } /*end resetWorkspaceState*/,

    /**
     * Clear error state.
     * Call from component when snackbar is dismissed.
     */
    clearError(): void {
      this.error = null;
    } /*end clearError*/,
  },
});

// HMR support for development
if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useTaskStore, import.meta.hot));
}
